# Generated by Django 5.2 on 2025-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='average_rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
