# Generated by Django 5.2 on 2025-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_room_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.CharField(default='City', max_length=50),
        ),
    ]
