# Generated by Django 5.2 on 2025-05-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='average_rating',
        ),
    ]
