# Generated by Django 5.2 on 2025-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_hotel_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
